config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"

  resources :standings, only: [:index]
  resources :games, only: [:index]
  resources :bests, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/games_facade.rb
class GamesFacade

  def teams
    { "STL" => "St. Louis Blues",
    "PHI" => "Philadelphia Flyers",
    "NAS" => "Nashville Predators",
    "TOR" => "Toronto Maple Leafs",
    "MIN" => "Minnesota Wild",
    "MON" => "Montreal Canadiens",
    "CGY" => "Calgary Flames",
    "CHI" => "Chicago Blackhawks",
    "LA" => "Los Angeles Kings",
    "SJ" => "San Jose Sharks",
    "BOS" => "Boston Bruins",
    "NJ" => "New Jersey Devils",
    "BUF" => "Buffalo Sabres",
    "CAR" => "Carolina Hurricanes",
    "NYI" => "New York Islanders",
    "FLA" => "Florida Panthers",
    "PIT" => "Pittsburg Penguins",
    "DET" => "Detriot Red Wings",
    "CBJ" => "Columbus Blue Jackets",
    "TB" => "Tampa Bay Lightning",
    "DAL" => "Dallas Stars",
    "COL" => "Colorado Avalanche",
    "WPG" => "Winnepeg Jets",
    "NYR" => "New York Rangers",
    "VEG" => "Vegas Golden Knights",
    "EDM" => "Edmonton Oilers",
    "OTT" => "Ottawa Senators",
    "ANA" => "Anaheim Mighty Ducks",
    "WAS" => "Washington Capitals",
    "ARI" => "Arizona Coyotes",
    "VAN" => "Vancouver Canucks"
   }
  end

  def results
    service.games
  end

  def service
    FantasyDataService.new
  end
end

app/models/standings_facade.rb
class StandingsFacade
  attr_reader :results

  def initialize
  end



  def results
    service.rankings
  end

  def service
    FantasyDataService.new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bests_controller.rb
class BestsController < ApplicationController

  def index

  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @games_facade = GamesFacade.new
    @games = @games_facade.results
    @teams = @games_facade.teams
  end

end

app/controllers/standings_controller.rb
class StandingsController < ApplicationController

  def index
    @standings_facade = StandingsFacade.new
    @results = @standings_facade.results
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/games/index.html.erb
<div class='games'>
  <h2>Today's Games</h2>
  <section class="list-games">
    <% @games.each do |game| %>
      <article class='game'>
        <br />
        <br />
        <br />
        <p><%= @teams[game[:AwayTeam]]%></p>
        <p> vs. </p>
        <p><%= @teams[game[:HomeTeam]] %> </p>
        <br />

      </article>
    <% end %>
  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YouHockey</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header>
      <button><%= link_to "YouHockey?", root_path%></button>
      <nav>
        <ul>
          <li><%= link_to "Best _____", bests_path%></li>
          <li><%= link_to "Current Standings", standings_path%></li>
          <li><%= link_to "Today's Games", games_path%></li>

        </ul>
      </nav>
    </header>
    <div class="hero-image">


    <%= yield %>
  </div>
  </body>
</html>

app/views/standings/index.html.erb
<div class='standings'>
  <h2>Current Standings</h2>
  <table id='rankings'>
    <tr>
      <th>Conference</th>
      <th>Division</th>
      <th>Team</th>
      <th>Wins</th>
      <th>Losses</th>
      <th>Percentage</th>
    </tr>
    <% @results.each do |result| %>
        <tr>
          <td><%= result[:Conference] %></td>
          <td><%= result[:Division] %></td>
          <td><%= result[:City]%> <%= result[:Name] %></td>
          <td><%= result[:Wins] %></td>
          <td><%= result[:Losses] %></td>
          <td><%= result[:Percentage] %></td>
        </tr>
    <% end %>
  </table>
</div>